### PR TITLE
Implement Player#getIPAddress

### PR DESCRIPTION
**Pull request by wolflord212312**
Started adding getPlayerIP as getIPAddress

Am Unable to build at this time, Potato will need to build and make sure its good.

### CODE REVIEW

**Comment by wolflord212312** [comment]
This is only for legacy!

**Comment by wolflord212312** [comment]
not hard to add to newer Versions either to my knowledge but done messing with it.

**Comment by wolflord212312** [comment]
```
/**
     * {@inheritDoc}
     */
    @Override
    public String getIPAddress(){
        return ((EntityPlayerMP) player).getPlayerIP();
    }
```

Copy to 1.12
Copy to 1.13


1.14 moves to net.minecraft.entity.player.ServerPlayerEntity from net.minecraft.entity.player.EntityPlayerMP

**Comment by wolflord212312** [comment]
@p0t4t0sandwich Should be good to go.

**Comment by wolflord212312** [comment]
Only doing forge for now as i dont use other Modding API's will look at bukkit when i need to but if im using bukkit i still dont need it for my stuff, But for taterUtils you may want to add it

**Comment by wolflord212312** [comment]
Why not doing fabric too wont touch sponge

**Comment by wolflord212312** [comment]
@Override
    public String getIPAddress(){
        return ((ServerPlayerEntity) player).getip();
    }
    
    for some reason this is not useablee in 1.14+ even tho it is in all javadocs to latest

**Comment by wolflord212312** [comment]
Ok that is all i will do for this
Feel free to merge

**Comment by p0t4t0sandwich** [comment]
I'll finish the implementations, then merge

**Pull request merged**
